### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/exam-finder#1]

**Comment by jotasprout** [comment]
I can format this properly -- is there anything else you need for it?

**Comment by anasvakyathodi** [comment]
@jotasprout, Any better changes are accepted.

**Comment by jotasprout** [comment]
Awesome. Please assign me this task and I'll get started right away.

**Comment by anasvakyathodi** [comment]
Do the magic 🪄

**Comment by jotasprout** [comment]
I don't see the "compare across forks" button that used to be on a repos main page or even the Compare button. Do I have perms to make a branch on your repo?

**Comment by anasvakyathodi** [comment]
you can create a branch after cloning the repo and push that branch for pull request.

**Comment by jotasprout** [comment]
Oh I submitted the PR a few hours ago. Did it not go through?

**Comment by anasvakyathodi** [comment]
@jotasprout its merged now, Thank you for your contribution.
